kind: pipeline
type: kubernetes
name: default

# clone:
#   disable: true

steps:
  - name: test
    image: bitnami/git:latest
    commands:
      - echo "hello"
      # - git clone https://github.com/LouisKamp/rust-test .
      # - git checkout $DRONE_COMMIT
