kind: pipeline
type: kubernetes
name: default

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - cat /etc/resolv.conf
      - ping google.com
      # - git clone https://github.com/LouisKamp/rust-test
      # - git checkout $DRONE_COMMIT
