kind: pipeline
type: kubernetes
name: default

clone:
  disable: true

steps:
  - name: clone
    image: bitnami/git:latest
    commands:
      - git clone https://github.com/LouisKamp/rust-test
      - git checkout $DRONE_COMMIT
