kind: pipeline
type: kubernetes
name: default

# clone:
#   disable: true

steps:
  - name: test
    image: rust:1.67-slim
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all
